In [1]:
import numpy as np

# 1. How to create an empty and a full Numpy array?

In [2]:
emp_arr = np.empty((1,4))
print(emp_arr)

[[0.00000000e+000 9.33432291e-312 9.33432291e-312 9.33432291e-312]]


In [3]:
full_arr = np.full((3,4),8)
print(full_arr)

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


# 2. Create a Numpy array filled with all zeros

In [5]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# 3. Create a Numpy array filled with all ones

In [6]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# 4. Check whether a Numpy array contains a specified row

In [9]:
num = np.arange(20)
print(num)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [10]:
arr = np.reshape(num, [4,5])
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [11]:
print([0, 1, 2, 3, 4] in arr.tolist())

True


In [12]:
print([0, 1, 2, 8, 4] in arr.tolist())

False


In [13]:
print([15, 16, 17, 18, 19] in arr.tolist())

True


# 5. How to Remove rows in numpy array that contains non-numeric values?

In [14]:
import numpy as np

In [19]:
arr = np.array([[0, 1, 2, 3],
                [5, 6, np.nan, np.nan],
               [8, 9, 10, 11]])
print(arr)

[[ 0.  1.  2.  3.]
 [ 5.  6. nan nan]
 [ 8.  9. 10. 11.]]


In [20]:
result = arr[~np.isnan(arr).any(axis = 1)]
print(result)

[[ 0.  1.  2.  3.]
 [ 8.  9. 10. 11.]]


# 6. Remove single-dimensional entries from the shape of an array

In [27]:
import numpy as np
x = np.ones((3, 1, 4))
print(x)
x.shape

[[[1. 1. 1. 1.]]

 [[1. 1. 1. 1.]]

 [[1. 1. 1. 1.]]]


(3, 1, 4)

In [26]:
print(np.squeeze(x).shape)

(3, 4)


# 7. Find the number of occurences of a sequence in a Numpy array

In [30]:
arr = np.array([[2, 8, 9, 4],
                [9, 4, 9, 4],
                [4, 5, 9, 7],
                [2, 9, 4, 3]])
result = repr(arr).count("9, 4")
print(result)

4


# 8. Find the most frequent value in a Numpy array

In [31]:
arr = np.array([1, 2, 3, 4, 5, 1, 2, 1, 2, 2, 2, 2, 2])
print(arr)
print(np.bincount(arr).argmax())

[1 2 3 4 5 1 2 1 2 2 2 2 2]
2


# 9. Combining a one and a two-dimensional Numpy Array

In [35]:
arr1 = np.array([4, 5, 6])
arr1.shape

(3,)

In [36]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
arr2.shape

(3, 3)

In [37]:
arr1 + arr2

array([[ 5,  7,  9],
       [ 8, 10, 12],
       [11, 13, 15]])

# 10. How to build an array of all combinations of two Numpy arrays?

In [40]:
arr1 = np.array([1, 2])
arr2 = np.array([4, 6])
print("Array 1 :", arr1)
print("Array 2 :", arr2)
arr3 = np.array(np.meshgrid(arr1, arr2)).T.reshape(-1, 2)
print(arr3)

Array 1 : [1 2]
Array 2 : [4 6]
[[1 4]
 [1 6]
 [2 4]
 [2 6]]


# Function 1 - np.concatenate

In [41]:
arr1 = [[1, 2],
        [3, 4]]
arr2 = [[5, 6, 7],
        [8, 9, 10]]
np.concatenate((arr1, arr2), axis = 1)

array([[ 1,  2,  5,  6,  7],
       [ 3,  4,  8,  9, 10]])

In [44]:
arr1 = [[1, 2, 5],
        [3, 4, 8]]
arr2 = [[5, 6, 7],
        [8, 9, 10]]
np.concatenate((arr1, arr2))

array([[ 1,  2,  5],
       [ 3,  4,  8],
       [ 5,  6,  7],
       [ 8,  9, 10]])

# Function 2 - np.arange

In [47]:
arr = np.arange(1, 60)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59]


# Function 3 - np.reshape

In [48]:
arr = np.arange(30)
arr2 = np.reshape(arr, [6,5])
print(arr2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


# Function 4 - np.zeros, np.ones and np.full

In [50]:
arr = np.zeros((3, 4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [53]:
arr = np.ones((5, 4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [54]:
arr = np.full((5,6), 8)
print(arr)

[[8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]]


# Function 5 - np.linspace and np.eye

In [55]:
arr = np.linspace(2, 29, 8)
print(arr)

[ 2.          5.85714286  9.71428571 13.57142857 17.42857143 21.28571429
 25.14285714 29.        ]


In [56]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Function 6 - np.min and np.max

In [58]:
arr = np.array([4, 9, 10])
a = np.min(arr)
print(a)

4


In [59]:
arr = np.array([4, 9, 10])
a = np.max(arr)
print(a)

10


# Function 7 - np.mean and np.median

In [60]:
arr = np.array([1, 2, 3])
a = np.mean(arr)
print(a)

2.0


In [62]:
arr = np.array([1, 2, 3, 5, 6])
a = np.median(arr)
print(a)

3.0


# Function 8 - np.dot

In [63]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

dot_product = np.dot(arr1, arr2)
print(dot_product)

32
